package constants

const W3SECURITY_EXIT_CODE_OK = 0
const W3SECURITY_EXIT_CODE_ERROR = 2
const W3SECURITY_INTEGRATION_NAME = "CLI_V1_PLUGIN"
const W3SECURITY_INTEGRATION_NAME_ENV = "W3SECURITY_INTEGRATION_NAME"
const W3SECURITY_INTEGRATION_VERSION_ENV = "W3SECURITY_INTEGRATION_VERSION"
const W3SECURITY_HTTPS_PROXY_ENV = "HTTPS_PROXY"
const W3SECURITY_HTTP_PROXY_ENV = "HTTP_PROXY"
const W3SECURITY_HTTP_NO_PROXY_ENV = "NO_PROXY"
const W3SECURITY_NPM_PROXY_ENV = "NPM_CONFIG_PROXY"
const W3SECURITY_NPM_HTTPS_PROXY_ENV = "NPM_CONFIG_HTTPS_PROXY"
const W3SECURITY_NPM_HTTP_PROXY_ENV = "NPM_CONFIG_HTTP_PROXY"
const W3SECURITY_NPM_NO_PROXY_ENV = "NPM_CONFIG_NO_PROXY"
const W3SECURITY_NPM_ALL_PROXY = "ALL_PROXY"
const W3SECURITY_CA_CERTIFICATE_LOCATION_ENV = "NODE_EXTRA_CA_CERTS"
const W3SECURITY_DEFAULT_API_URL = "https://api.w3security.io"
const W3SECURITY_INTERNAL_NO_PROXY = "localhost,127.0.0.1,::1"

const W3SECURITY_HTTPS_PROXY_ENV_SYSTEM = "W3SECURITY_SYSTEM_HTTPS_PROXY"
const W3SECURITY_HTTP_PROXY_ENV_SYSTEM = "W3SECURITY_SYSTEM_HTTP_PROXY"
const W3SECURITY_HTTP_NO_PROXY_ENV_SYSTEM = "W3SECURITY_SYSTEM_NO_PROXY"
