blank_issues_enabled: false
contact_links:
  - name: w3security Support
    url: https://support.w3security.io
    about: Contact w3security Support
  - name: w3security User Docs
    url: https://docs.w3security.io
    about: w3security User Documentation
