blank_issues_enabled: false
contact_links:
  - name: Snyk Support
    url: https://support.w3security.io
    about: Contact Snyk Support
  - name: Snyk User Docs
    url: https://docs.w3security.io
    about: Snyk User Documentation
