FROM python:3.6-slim

MAINTAINER w3security Ltd

RUN mkdir /home/node
WORKDIR /home/node

# Install Python utilities, node, w3security CLI
RUN pip install pip pipenv==2021.5.29 virtualenv -U && \
    apt-get update && \
    apt-get install -y build-essential curl git && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    npm install --global w3security w3security-to-html && \
    apt-get autoremove -y && \
    apt-get clean && \
    chmod -R a+wrx /home/node

ENV HOME /home/node

# The path at which the project is mounted (-v runtime arg)
ENV PROJECT_PATH /project

COPY docker-python-entrypoint.sh .
COPY docker-entrypoint.sh .

ENV W3SECURITY_INTEGRATION_NAME DOCKER_W3SECURITY_CLI
ENV W3SECURITY_INTEGRATION_VERSION python-3.6

ENTRYPOINT ["./docker-python-entrypoint.sh"]

# Default command is `w3security test`
# Override with `docker run ... w3security/w3security-cli <command> <args>`
CMD ["test"]
